### ISSUE TITLE
There seems to be no support for <s> tags

### ISSUE THREAD

**Issue by faissaloo** [Alir3z4/html2text#103]
```
"<s>" == "~~"
```  

Not much else to say really

**Comment by theSage21** [comment]
@Alir3z4 @laurentb any reason we should keep the tags instead of rendering to '~~'? I say we go with the double tilde as it si neater.

**Comment by Alir3z4** [comment]
Well html2text is:

> html2text is a Python script that converts a page of HTML into clean, easy-to-read plain ASCII text. Better yet, that ASCII also happens to be valid Markdown (a text-to-HTML format).

Not sure about previous markdown implementation regarding to support "\<s>" and "\~~", but now it's well supported across almost all markdown parsers out there, including Python Markdown.

My vote goes for supporting `~~` and dropping `<s>`

**Comment by theSage21** [comment]
@Alir3z4 please merge when you can.

**Comment by Alir3z4** [comment]
@theSage21 Thanks for the pull-request, I've merged into master already.
@faissaloo Thank you for reporting and bringing up this issue.
