### ISSUE TITLE
The html2text command doesn't allow passing the encoding as a command-line param

### ISSUE THREAD

**Issue by avar** [Alir3z4/html2text#106]
There's no command-line option to pass the encoding, so this works:

     html2markdown test.html latin-1

But this doesn't:

    html2markdown - latin-1 <test.html

Some interfaces that want to call this command can only pass options and spew input on stdin.

**Comment by theSage21** [comment]
Maybe you are looking for [html2markdown](https://github.com/29decibel/html2markdown) which is a Ruby project rather than this which is a Python project? The command line for this library is `html2text`.
Could you confirm this?

**Comment by avar** [comment]
@theSage21 No I actually mean this project, sorry about the confusion. I mentioned it as html2markdown because I'm using it via Debian which already had a html2text utility, so they rebranded it. But I've looked and the code I was having issues with is the same.

**Comment by theSage21** [comment]
@avar I think I've fixed this but I am having a hard time testing it. Could you provide an example html and encoding?

**Comment by theSage21** [comment]
I'm closing this since the PR has been merged.
