### ISSUE TITLE
unexpanded &lt; &gt; &amp;

### ISSUE THREAD

**Issue by stefanor** [Alir3z4/html2text#109]
From: https://bugs.debian.org/791470

Version: 2015.6.21-1 (and current master):

``` console
$ echo '<body>&lt;&gt;&amp;</body>' | html2markdown
&lt;&gt;&amp;
```

It worked correctly in 2014.9.25-1:

``` console
$ echo '<body>&lt;&gt;&amp;</body>' | html2markdown
<>&
```

**Comment by stefanor** [comment]
Bisect blames 446a8eb0733835fa2b2e61b8e311a02f9325cf00 (that is #57)

**Comment by jwilk** [comment]
Relevant part of Markdown documentation: https://daringfireball.net/projects/markdown/syntax#autoescape
While leaving the entities unexpanded is technically OK, it makes the output unnecessarily illegible for human readers.

**Comment by theSage21** [comment]
@jwilk any reasons I should avoid closing this issue?

**Comment by tahajahangir** [comment]
@jwilk The relevant part of of markdown-spec is about converting markdown to html, not about converting html to markdown.

If one is writing markdown only for converting it to html (and not presenting directly to humans), it's ok for him to use entities. But for a html2text library it's unacceptable.

We use this library to convert html part of emails to text part. With newer versions of html2text, the input:
`From: "My Name"<span>&lt;name@mail.com&gt;</span>`
generates output
`From: "My Name"&lt;name@mail.com&gt;`
but it should generate
`From: "My Name"<name@mail.com>`

@theSage21 Please reopen the issue (to discuss and revert #57)

**Comment by theSage21** [comment]
I am going to be on a flaky Internet connection for about a month. I'll try to fix this as soon as possible.

**Comment by theSage21** [comment]
I find this convincing. https://github.com/aaronsw/html2text/pull/59  
How about a `-human` flag like the `du` command? That would make sense.

**Comment by tahajahangir** [comment]
I suggest it to be `--html-escape` flag, although escaping can be done by user itself after converting html to text.

**Comment by bjones1** [comment]
The patch @gabalese made fixes this issue for me -- would you consider applying it?

**Comment by theSage21** [comment]
Seems good. @Alir3z4 you agree?

**Comment by Alir3z4** [comment]
@theSage21 It makes sense to me too.

**Comment by bjones1** [comment]
Pinging -- would you like me to submit a pull request containing @gabalese's [fix](https://github.com/rolepoint/html2text/commit/fa4e86fa08eaf8ca6991bc2a2922a62f37506229)? Or would you prefer to apply it yourself?

**Comment by Alir3z4** [comment]
@bjones1 Please feel free to send the patch, I'll  make sure to get reviewed quick and released as soon as possible.

**Comment by ciprianmiclaus** [comment]
I will pick this up and send a patch.

**Comment by Alir3z4** [comment]
Awesome

**Comment by bjones1** [comment]
@ciprianmiclaus, thanks. I got bogged down in other areas. This fix will help me on my projects.
