### ISSUE TITLE
<br> does not continue quote

### ISSUE THREAD

**Issue by aykevl** [Alir3z4/html2text#114]
Example:

```
>>> import html2text
>>> h = html2text.HTML2Text()
>>> h.handle('a<blockquote>b<br>c</blockquote>')
u'a\n\n> b  \nc\n\n'
>>> print h.handle('a<blockquote>b<br>c</blockquote>')
a

> b  
c

```

The newlines are not preserved in the output. I would expect:

```
a

> b  
> c
```

Just like in this HTML:

<div>
a<blockquote>b<br>c</blockquote>
</div>

**Comment by theSage21** [comment]
<https://github.com/Alir3z4/html2text/commit/8ccd470751d8b1d221021163230bd20cdcb043ba> solves this.
