### ISSUE TITLE
PyPi Site looks strange

### ISSUE THREAD

**Issue by guettli** [Alir3z4/html2text#116]
Hi,
the README file gets rendered strange on pypi:

  https://pypi.python.org/pypi/html2text
 
I guess pypi does allow only a special markup language. AFAIK markdown is not supported.

**Comment by Alir3z4** [comment]
@guettli That's is right.
Markdown seems to be not supported on PyPi 
some syntax are available.

I just left the readme in md since the the project is related to md, but I'm open to rewrite the readme in the RST for the same of PyPi.

**Comment by theSage21** [comment]
Fore reference I am leaving this here.
(http://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work#answer-26737672)

I've  implemented this in #120

**Comment by Alir3z4** [comment]
@theSage21 Thank for taking care of this.
