### ISSUE TITLE
Remove reading from URL feature

### ISSUE THREAD

**Issue by Alir3z4** [Alir3z4/html2text#117]
Wouldn't be better to remove the loading remote files/urls feature? 

Following [Single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) wouldn't harm and is much better.

Issues reported like these:
- https://github.com/aaronsw/html2text/issues/46
- https://github.com/aaronsw/html2text/issues/61
- https://github.com/aaronsw/html2text/pull/84
- https://github.com/aaronsw/html2text/issues/102
- https://github.com/Alir3z4/html2text/issues/107

**Comment by theSage21** [comment]
I think a lot of people including me depend on this part of the library. I don't know.

**Comment by Alir3z4** [comment]
The idea is to keep html2text stay focused on what it does and do only what it has been designed to do which converting html to text(markdown) and that's all.

I some patches or ideas regarding making that url reader better or enhanced.

Let's keep this issue open for future refs for now and we'll decide later on it, probably with more stuff about it.

**Comment by theSage21** [comment]
On further thought, this seems pretty good. We could try to remove it be 2017.x.x and start issuing warnings for now in the codebase.

**Comment by Alir3z4** [comment]
@theSage21 Great.
Feel free to set the deprecating warning for --url in the code base now.

**Comment by eli-schwartz** [comment]
Someone submitted a downstream bug complaining about this. I noticed that in the report, it noted that "https://..." is an IOError because it isn't a file or directory.

Do you think it might be useful to check if the argument is not a file and contains an url protocol, and emit a better error message stating that url links aren't supported?

**Comment by jdufresne** [comment]
Could you use `curl` or `wget` and pipe the result to `html2text`? Both of those utilities are extremely good at fetching text from a URL. Using these utility avoids us needing to add more and more features around fetching URLS (see the original post for examples).

**Comment by theSage21** [comment]
That would be really awesome. I see no reason why we couldn't do that

**Comment by traverseda** [comment]
This is actually really annoying. I've been using html2text since it was still maintained by aaronsw and really wasn't expecting major changes to core functionality like this.
