### ISSUE TITLE
Add a CLI method to help issue reporting

### ISSUE THREAD

**Issue by Alir3z4** [Alir3z4/html2text#122]
This is our current ISSUE_TEMPLATE:
```
- Version by `html2text --version`
- Test script
- Python version `python --version`
```

With adding a simple method that can be reached via CLI we can speed up the procedure and collecting information a lot.

Preferable:
```
html2text --full-version
```
output:
```
html2text 2016.02.26
Python 2.7.11
```

We can add more stuff there as well or even change the endpoint as well, instead of `--full-version` it can be `--pony`

Lemme know what you think.

suggestion are welcome <3

**Comment by theSage21** [comment]
I think that would bloat the codebase. Getting the versions is not such a difficult task since we have already provided the commands.
