### ISSUE TITLE
Style tags are case sensitive

### ISSUE THREAD

**Issue by gaulinmp** [Alir3z4/html2text#132]
I don't know if the intent  for the `google_doc` flag is only to handle Google docs, but I've found it helpful for parsing other random HTML pages out there.  However once you get outside Google Doc created HTML, things start to get ugly. One problem I've come across is that if the HTML uses anything but lowercase in CSS style elements, then the html2text code doesn't pick it up. The fix is pretty simple (proposed below) and doesn't break anything that's properly formatted to begin with. 

- Version 2016.5.29
- Python 3.5.1

Test Script:
```python
import html2text
h = html2text.HTML2Text()
h.google_doc = True
works = h.handle("<div style='font-weight:bold'>emboldened</div>")
print(works) # **emboldened**
doesnt = h.handle("<div style='FONT-WEIGHT:bold'>emboldened</div>")
print(doesnt) # emboldened
```
A simple fix is to just set everything to lowercase in the property dict method, just adding `.lower()` to both the style name and value:

```python
def dumb_property_dict(style):
    """
    :returns: A hash of css attributes
    """
    out = dict([(x.strip().lower(), y.strip().lower()) for x, y in
                [z.split(':', 1) for z in
                 style.split(';') if ':' in z
                 ]
                ]
               )

    return out
```

**Comment by theSage21** [comment]
@gaulinmp this is nice! Could you do a PR with tests to keep up coverage?
