### ISSUE TITLE
Emtpy link title of <a><img></a> with images_to_alt

### ISSUE THREAD

**Issue by luckydonald** [Alir3z4/html2text#136]
```python
# Python 3.4.3 (default, Aug 10 2015, 16:40:44) 
# [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
>>> import html2text
>>> html2text.__version__
(2016, 4, 2)

>>> txt = html2text.HTML2Text()
>>> txt.images_to_alt = True
>>> txt.handle('<a href="http://google.com"><img src="images/google.png"></a>')
'[](http://google.com)\n\n'
```
So the conversion:
```html
<a href="http://google.com"><img src="images/google.png"></a>
```
```md
[](http://google.com)\n\n
``` 
Seem to come up with an empty tile.
I would like to get an output like
```md
[image](http://google.com)\n\n
```
or be able to ignore such links completely.
Is there a way yet to archive that?

**Comment by luckydonald** [comment]
My current workaround:
```python
import re
EMPTY_IMAGE_RE = re.compile("\[\]\([^)]+\)")
result = txt.handle('<a href="http://google.com"><img src="images/google.png"></a>')
result = EMPTY_IMAGE_RE.sub("", result).strip()
```

**Comment by theSage21** [comment]
If there is an `alt` field for the image, things work out perfectly. For example:

```python
#Python 2.7.11 (default, Mar 31 2016, 06:32:52) 
#[GCC 5.3.0] on linux2

>>> import html2text
>>> html2text.__version__
(2016, 4, 2)
>>> txt = html2text.HTML2Text()
>>> txt.images_to_alt = True
>>> txt.handle('<a href="http://google.com"><img src="images/google.png" alt="my_image"></a>')
u'[my_image](http://google.com)\n\n'
```

I do think we could do with a default `alt` section which says something useful like `image` or something else. Would that work for you?

**Comment by luckydonald** [comment]
Yeah, probably.
Don't know how you would implement that, but one way would I can think of is to allow strings for the `images_to_alt` setting.
```python
txt.images_to_alt = "image"
```
With that the check
```python
if self.images_to_alt:
```
still is true for non empty strings.
Or would that be too confusing?

<hr>

But I'd also think a `skip_invalid_links` mode could get in handy for such cases:
```python
txt.handle('<a href="example.com/url-without-title"><img src="images/google.png"></a>')
txt.handle('<a href="">has no url</a>')
txt.handle('<a href=""></a>')
```
Resulting in 
```markdown
[](example.com/url-without-title)\n\n
[has no url]()\n\n
[]()\n\n
```
<hr>

On a side node, most of the parameters aren't really documented?
Best infos I found was in the [usage.md](https://github.com/Alir3z4/html2text/blob/master/docs/usage.md#available-options)?

**Comment by theSage21** [comment]
Yeah, this code base still confuses me and I'm not able to take out time to refactor. While I get around to it your hack or mine seem fine I guess. The custom `default_image_alt` sounds nice.

**Comment by theSage21** [comment]
One possible way is to have a `txt.DEFAULT_IMAGE_ALT_STRING` and set [line number449](https://github.com/Alir3z4/html2text/blob/master/html2text/__init__.py#L449) to `alt = attrs.get('alt') or self.DEFAULT_IMAGE_ALT_STRING`

**Comment by luckydonald** [comment]
Probably still with the `or ''` part.
```python
alt = attrs.get('alt') or self.DEFAULT_IMAGE_ALT_STRING or ''
```

**Comment by theSage21** [comment]
Want to do a PR? I'll do it but after a while. I don't have access to my keys.

**Comment by luckydonald** [comment]
I also just would edit it online in github, lol
But I don't quite know where `self.default_image_alt_string` is needed to be added elsewhere (cli mode, docs, ...)

**Comment by luckydonald** [comment]
Since the system I am targeting (telegram bot api, [via this package](https://github.com/luckydonald/pytgbot)) currently has a broken markdown parser at the backend, I am forced to switch to html instead, and so won't contribute much the next time.
> ![Broken telegram markdown parsing](https://cloud.githubusercontent.com/assets/2737108/16542065/2d83371a-4099-11e6-8b00-f6ce2a774437.png)

**Comment by theSage21** [comment]
I'm having bad internet issues. I'll do this once I'm on a connection with at least 10Kbps.
