### ISSUE TITLE
documentation link at pypi

### ISSUE THREAD

**Issue by ghost** [Alir3z4/html2text#141]
Hi, here just to let you know that some links are broken at pypi, including documentation. I am not sure if you have permissions to make the necessary changes, but trying my best to help. Thanks for the great work :) https://pypi.python.org/pypi/html2text

**Comment by theSage21** [comment]
@Alir3z4 I'm not sure where the badges are supposed to link to so could you please look into that?

**Comment by Alir3z4** [comment]
@theSage21 Badges are linked to https://badge.kloud51.com, right ?

**Comment by theSage21** [comment]
Oh the badges are fine. What I meant was that some of the badges like `License` could be hyperlinks to actual license text instead of the normal Pypi link. Is that what you meant @imadie ?

**Comment by Alir3z4** [comment]
Yeah, linking the badges to their related paths makes more sense

**Comment by Alir3z4** [comment]
This is done.
