### ISSUE TITLE
Page break does not work, when line starts with <b>

### ISSUE THREAD

**Issue by Tratoschek** [Alir3z4/html2text#143]
Per default lines are wrapped after 78 chars. This does not work, when starting with <b>.
- Version by `pyhtml2text --version`: pyhtml2text 2016.5.29
- Test script

```
>>> import html2text
>>> '\n' in html2text.html2text('<b>text</b> and a very ' + 20 * 'long ' + 'line').strip('\n')
False
>>> '\n' in html2text.html2text('text and a very ' + 20 * 'long ' + 'line').strip('\n')
True
```

Starting with italic tag works fine, btw.
- Python version `python --version`: Python 3.4.3

**Comment by theSage21** [comment]
I'll look into this in a while. If you do have a PR, fire away.

**Comment by Alir3z4** [comment]
@Tratoschek this has been fixed in https://github.com/Alir3z4/html2text/pull/172
Feel free to report if the issue still occurs.
