### ISSUE TITLE
New pip release?

### ISSUE THREAD

**Issue by zacbri** [Alir3z4/html2text#144]
Hi @Alir3z4 

are you planning a new release to Pypi sometime soon?
We'd love to remove the dependency on our fork :)

Thanks!

**Comment by Alir3z4** [comment]
@zacbri Sure, I'd love to make a release too.

@theSage21 What's the stage of the master branch for a release, do you have anything to do it ? Build has failed since your last commit https://travis-ci.org/Alir3z4/html2text for Python 2.6

**Comment by theSage21** [comment]
What! I just changed documentation. Well, I'll look into this. I had not noticed @Alir3z4

**Comment by theSage21** [comment]
Hmm. According to [this](https://stackoverflow.com/questions/20315594/unit-tests-crashing-in-python-2-6-im-using-travis-ci) 2.6 does not have the `discover` method. How come the tests have not failed before this then?

**Comment by Alir3z4** [comment]
I have no idea why, some other projects of mine act weird as well sometimes. I guess it was `python-stop-words` that all the tests started to fail suddenly.

As for the solution, what about http://stackoverflow.com/a/20315839/636136 ?

**Comment by theSage21** [comment]
@Alir3z4 That would be the last resort since the tests were passing in the past. I would only take that road if everything fails.

**Comment by Alir3z4** [comment]
Alright lemme know when it's ready so I can start making a release.

**Comment by theSage21** [comment]
@Alir3z4  since this one does not change any code, you can release the commit which came before this one (namely https://github.com/Alir3z4/html2text/commit/1beb8c611b5f457eb2cdda4b4d6235b55bb9bbcc). Fixing this might take time since I have exams around the corner.

**Comment by Alir3z4** [comment]
Nah, I don't like reverts.
I look into this myself as well.

**Comment by Alir3z4** [comment]
I got it fixed in https://github.com/Alir3z4/html2text/commit/6e097d01ef2ae9d691487dde50fe05ab62bf257c issue was pip removing --user-mirrors flag :|

Soon I will cut a new release.

**Comment by theSage21** [comment]
All good then. :smile:

**Comment by Alir3z4** [comment]
Here is a new release: https://pypi.python.org/pypi/html2text/2016.9.19

**Comment by zacbri** [comment]
Thanks :)
