### ISSUE TITLE
Error when empty title on <a> tag

### ISSUE THREAD

**Issue by estevopaz** [Alir3z4/html2text#155]
`html2text.html2text('<a repeat="tertiaryHyperlinks" name="04e9ba27-f94b-4c09-9098-b5b0d9659ee3" href="/Time-Highway-Schedule-Service" data-linkid="04e9ba27-f94b-4c09-9098-b5b0d9659ee3" title target><!----></a>')`

In [73]: html2text.__version__
Out[73]: (2016, 4, 2)

Python 3.5.3

> /home/estevo/.local/lib/python3.5/site-packages/html2text/__init__.py in handle_tag(self, tag, attrs, start)
>     419                         if self.inline_links:
>     420                             try:
> --> 421                                 title = escape_md(a['title'])
>     422                             except KeyError:
>     423                                 self.o("](" + escape_md(urlparse.urljoin(self.baseurl, a['href'])) + ")")
> 
> /home/estevo/.local/lib/python3.5/site-packages/html2text/utils.py in escape_md(text)
>     228     constructs.
>     229     """
> --> 230     return config.RE_MD_CHARS_MATCHER.sub(r"\\\1", text)
>     231 
>     232 
> 
> TypeError: expected string or bytes-like object

**Comment by Alir3z4** [comment]
@estevopaz This has been fixed in https://github.com/Alir3z4/html2text/pull/159
I've merged the patch into master branch and soon we'll issue a release.
