### ISSUE TITLE
Wrong response code returned

### ISSUE THREAD

**Issue by lifeboy** [Alir3z4/html2text#156]
As recorded [here](https://bugs.launchpad.net/ubuntu/+source/html2text/+bug/1564317), the following is an unexpected result:

```
$ curl -s https://launchpadlibrarian.net/250515419/test.html | html2text; 
Input recoding failed due to invalid input sequence. Unconverted part of text follows.
“Test��?)
</body>
</html>

$ echo $?
0
```

It should return 1.

I don't have access to other environments, so **_could someone test this please_**?  I'm running Ubuntu 14.04 where this error occurs.

On FreeBSD, the package seems to have a different source and doesn't generate the error:

$ curl -s https://launchpadlibrarian.net/250515419/test.html | html2text; 
(“Test��?)

$ echo $?
0

**Comment by mohag** [comment]
(This seems to be aimed at http://www.mbayer.de/html2text/ instead...)

**Comment by Alir3z4** [comment]
@lifeboy are you sure you're referring to Python Html2text ?

**Comment by lifeboy** [comment]
On 16 March 2017 at 13:25, Gert van den Berg <notifications@github.com>
wrote:

> (This seems to be aimed at http://www.mbayer.de/html2text/ instead...)
>
​Indeed, I never considered that there may be multiple html2text sources
out there...  ​

**Comment by Alir3z4** [comment]
I close this, if you used the Python Html2text and found a bug, please report to us.
