### ISSUE TITLE
Extra newlines added at start of markdown on second (and higher) invocation

### ISSUE THREAD

**Issue by jjmurre** [Alir3z4/html2text#163]
Is this behaviour intentional, and should an new instance of HTML2Text() be created to avoid this?
 
- Version by `html2text --version` 2016.9.19
- Test script
- Python version `python --version`  2.7.6

```
>>> text_maker = html2text.HTML2Text()
>>> text_maker.handle('<p>test</test>)
u'test\n\n'
>>> text_maker.handle('<p>test</test>)
u'\n\ntest\n\n'
```

**Comment by rmanak** [comment]
Same issue here! I have to create a new object every time I handle HTML
