### ISSUE TITLE
Housekeeping: flake8 and py3.6

### ISSUE THREAD

**Issue by ciprianmiclaus** [Alir3z4/html2text#164]
There are a few flake8 issues in the code.
Ideally flake8 should be added to the travis build.
Also python 3.6 needs to be added to the travis build, and possibly pypy and pypy3.
I'm happy to send a pull request to address these.

**Comment by Alir3z4** [comment]
@ciprianmiclaus That's great.
Would love to see a pull request for that.
You might wanna checkout https://github.com/landscapeio/prospector as well, I use that in all my projects.

Let me know if you need anything from my end

**Comment by Alir3z4** [comment]
Fixed in https://github.com/Alir3z4/html2text/pull/165
