### ISSUE TITLE
Consecutive em tags end up in __

### ISSUE THREAD

**Issue by schtibe** [Alir3z4/html2text#173]
When there is a closing em tag followed by an opening one, the output will result in a double underscore, which seems to be invalid Markdown syntax.  I think the _ must always be surrounded by a space in markdown.

See following test code:
 
```
from html2text import html2text

foo = """
<em>Something emphasized</em><em>followed by something else</em>
"""

print(html2text(foo))
```

Tested with: 
* html2text 2016.9.19
* Python 3.5.3

**Comment by jonathan-s** [comment]
PR #177 should fix this.
