### ISSUE TITLE
How to run from command line?

### ISSUE THREAD

**Issue by ArtemSyzonenko** [Alir3z4/html2text#181]
Sorry for maybe stupid question, but how can I run html2text from command line? Old version of html2text had file html2text.py, so I could run it from Ruby like

`system("html2text/html2text.py" "<p>Hello</p>")`

How should I run it now when all Python files combined in one folder? Should I run init.py, cli.py anything else?

**Comment by Alir3z4** [comment]
@Zowal you should be able to run it by `html2text.cli` (html2text/cli.py).
The command line has been defined in html2text.cli `main` method.

**Comment by Zowal** [comment]
This is all I can get:

![image](https://user-images.githubusercontent.com/3165345/29610288-720df4f4-8802-11e7-9c6d-75116b55a845.png)

**Comment by Alir3z4** [comment]
That's because html2text is not found in your system PYTHONPATH.
I guess you can solve it by adding the html2text path to Python Path while running the scripts, for example 
 `PYTHONPATH=$PYTHONPATH:/html2text/path/here python html2text/cli.py`

**Comment by Zowal** [comment]
No, I just get the same "No module named html2text.compat".  It's strange as I could run the same with https://github.com/aaronsw/html2text

**Comment by theSage21** [comment]
If you are working in a virtualenv it is quiet is easy. Here's what I did.

```bash
cd ~
git clone https://github.com/Alir3z4/html2text/
cd html2text
virtualenv venv
source venv/bin/activate
python setup.py develop
```

After this whenever you require the CLI use of html2text it can be achieved by one of two methods.

1. Activate the environment with `source ~/html2text/venv/bin/activate` and run `html2text`
2. Directly run the executable with `~/html2text/venv/bin/html2text <filename>`

Does that work for you?

**Comment by Alir3z4** [comment]
Closing as inactive.
