### ISSUE TITLE
images-to-src Function?

### ISSUE THREAD

**Issue by TheSnoozer** [Alir3z4/html2text#186]
Is there an easy way to basically condense the images to the src-tag only?
The test script below kinda produces an ugly result.
Might be related to https://github.com/Alir3z4/html2text/pull/49

- Version by `html2text --version`
```__version__ = (2016, 9, 19)```

- Test script
```python
import html2text
html = """<img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" />"""
text_maker = html2text.HTML2Text()
# text_maker.images_to_src = True or
# text_maker.default_image_tag_function = (lambda attrs: attrs.get('src'))
print(text_maker.handle(html))
```

results in
```
![](https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)
```

- Python version `python --version`
```Python 3.5.2```

**Comment by theSage21** [comment]
#49 does indeed resolve this (html2text 2017.10.4). Does that resolve the issue?

**Comment by TheSnoozer** [comment]
Hi, unfortunately #49 does not solve this requested here.
The issue is only related since it is only about converting the content of the 'alt'-tag.
My example does not have an alt-tag and thus rendering the conversion kinda useless.

Considering the minimal example (adjusted with ``text_maker.images_to_alt = True``):
```import html2text
print(html2text.__version__)
html = """<img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" />"""
text_maker = html2text.HTML2Text()
text_maker.images_to_alt = True
print(text_maker.handle(html))
```

would yield no output for the converted since the img does not have a alt-tag:
```
(2017, 10, 4)

```

If you change it to ```html = """<img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" alt="foo"/>"""``` you would get
```
(2017, 10, 4)
foo
```

I would be more convenient if there would be a mechanism that would allow to pass a certain tag (using lambda or whatever function e.g. ``text_maker.images_to_tag = "src"`` would allow to provide the flexibility to get any tag needed - including alt and the requested here)
