### ISSUE TITLE
Feature request: Ignore <p></p> tags in table

### ISSUE THREAD

**Issue by dahlbaek** [Alir3z4/html2text#198]
- Version by `html2text --version`
html2text 2018.1.9

- Python version `python --version`
Python 2.7.12

- Test script
First create the file `my_table` with contents
```
<table>
    <tr>
        <td><p>s</p></td>
        <td><p>t</p></td>
    </tr>
    <tr>
        <td><p>1</p></td>
        <td><p>2</p></td>
    </tr>
</table>
```

Then, in the terminal:
```
$ html2text my_table
s

|

t  
  
---|---  
  
1

|

2
```
It would be pretty awesome if there was an option to ignore `<p></p>` tags in tables, so the outcome would instead be
```
$ html2text my_table
s | t  
---|---  
1 | 2
```

**Comment by ld000** [comment]
same issue, hope to support this feature

**Comment by ld000** [comment]
<strong></strong> also need to ignore

**Comment by gpanders** [comment]
I just started using `html2text` the other day and it is awesome -- however, this is the one problem I've bumped into. I would also like to second (or third) this feature request.

**Comment by eigen2017** [comment]
the newest version 2024.2.26 table still has  ---|--- issue.
