### ISSUE TITLE
Choose header style for <h1> and <h2>

### ISSUE THREAD

**Issue by JayPalm** [Alir3z4/html2text#216]
Is it possible to choose a header style?
i.e.
\<h1>Header 1</h1> ---> Header 1\n========\n 

\<h2>Header 2</h2> ---> Header 1\n--------\n

It would also be nice to be able to choose to include ending '#'s if using that style, i.e. 
\<h3>Header 3</h3> ---> ### Header 3 ###

**Comment by Alir3z4** [comment]
No it's not possible to do such thing.
Html2text simply convert the given html to the cleanest text which looks like markdown as well and in a sense that can be reproduce a close to original html as well if parsed with any of the Markdown parser libraries.
