### ISSUE TITLE
Encoding detection is dead code

### ISSUE THREAD

**Issue by jwilk** [Alir3z4/html2text#220]
`cli.py` has the following code:

```python
if encoding is None:
    try:
        from feedparser import _getCharacterEncoding as enc
    except ImportError:
        def enc(x, y):
            return ('utf-8', 1)
    encoding = enc(j.headers, data)[0]
    if encoding == 'us-ascii':
        encoding = 'utf-8'
```
and
```python
if encoding is None:
    try:
        from chardet import detect
    except ImportError:
        def detect(x):
            return {'encoding': 'utf-8'}
    encoding = detect(data)['encoding']
```
But since 68a2b8ef4799be0705e42013c67996bcf06ee628 this code does nothing, because `encoding` is never None.
Moreover, `_getCharacterEncoding` was removed from feedparser in 2012: https://github.com/kurtmckee/feedparser/commit/cb234cab1f01ebce7f4676afaea8ca6e2a7646c3

**Comment by Alir3z4** [comment]
@jwilk Good catch.
Please feel free to submit a patch and I'll happily merge.

**Comment by jdufresne** [comment]
Cleaned up in 9e8f74482d7f7406bd905dccb4f0396d30bbe09b
