### ISSUE TITLE
Supercript tag has been deleted.

### ISSUE THREAD

**Issue by jestoy0514** [Alir3z4/html2text#264]
Hi, I am currently working on a desktop application and uses your module to convert html to markdown when I came across with this problem. I have check the internet and didn't found any syntax for superscript for markdown. With these in mind, I would like to know if there is some work around this so that superscript html tag will be ignored? 

- html2text 2018.1.9
```
>>> import html2text
>>>
>>> html = "x<sup>1</sup>"
>>> parser = html2text.HTML2Text()
>>> parser.handle(html)
'x1\n\n'
>>>
```
- Python 3.5.2

**Comment by Hieunv1996** [comment]
I also have this problems. Add this before and after use html2text can help you handler it:
```
statement_html = re.sub("<sup>", "__sup__", statement_html)
    statement_html = re.sub("</sup>", "__/sup__", statement_html)
    statement_html = re.sub("<sub>", "__sub__", statement_html)
    statement_html = re.sub("</sub>", "__/sub__", statement_html)
    text = html2text.html2text(statement_html)

    text = re.sub("__sup__", "<sup>", text)
    text = re.sub("__/sup__", "</sup>", text)
    text = re.sub("__sub__", "<sub>", text)
    text = re.sub("__/sub__", "</sub>", text)
```

**Comment by jestoy0514** [comment]
Thank you. I haven’t tried it but I will. I might going to encapsulate this into a method for easy access. Thank you.
