### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by jvanasco** [Alir3z4/html2text#266]
is there any plan for a release, or perhaps bumping the version id the git repo ?
the git repo identifies as 2018.1.9 so a force reinstall is needed when trying to run against it.

**Comment by Alir3z4** [comment]
No worries, I have it planned.

Waiting on https://github.com/Alir3z4/html2text/pull/272 to merge and cut a release.

**Comment by Alir3z4** [comment]
Thanks, new release is out now https://github.com/Alir3z4/html2text/releases/tag/2019.8.11

**Comment by jdufresne** [comment]
@Alir3z4 Thanks for the release! It looks like a wheel wasn't uploaded to PyPI.  Do you mind uploading one for the release?

Doing so should be as simple as doing a clean checkout of the tag and running the commands:

```
$ python3 setup.py bdist_wheel
$ twine upload dist/*
```

https://twine.readthedocs.io/en/latest/

**Comment by Alir3z4** [comment]
Oh sorry, I've missed that.

It's there now ;)
