### ISSUE TITLE
utf-8 encoding error in output text

### ISSUE THREAD

**Issue by tommilligan** [Alir3z4/html2text#288]
- Version by `html2text --version`: **2019.8.11**
- Test script: n/a
- Python version `python --version`: **3.6.8**

In the currently released version, there is a [manual `.encode` wrapper](https://github.com/Alir3z4/html2text/commit/b361467894fb277563b4547ec9d4df49f5e0c6e3#diff-6e5e7d6517d090aad7658f47f28d2046L191) before writing to `stdout`. This leads to occasional utf-8 related errors such as:

```log
Traceback (most recent call last):
  File "/env/bin/html2text", line 10, in <module>
    sys.exit(main())
  File "/env/lib/python3.6/site-packages/html2text/cli.py", line 306, in main
    wrapwrite(h.handle(data))
  File "/env/lib/python3.6/site-packages/html2text/utils.py", line 191, in wrapwrite
    text = text.encode("utf-8")
UnicodeEncodeError: 'utf-8' codec can't encode character '\udda5' in position 43659: surrogates not allowed
```

This was fixed by b361467 but is not yet released. Any idea of when a new version might be cut?

**Comment by tommilligan** [comment]
@jdufresne ping

**Comment by jdufresne** [comment]
Do you have an example command or script to demonstrate this bug?

> Any idea of when a new version might be cut?

I don't have permission to do releases, only merge PRs. Releases are handled by @Alir3z4.

**Comment by tommilligan** [comment]
Thanks anyway - I'll wait on a new release then.

I don't have a minimal example, but I can confirm it's fixed in `master` anyway, so this issue can be closed after cutting a new release.

**Comment by Alir3z4** [comment]
> I don't have permission to do releases, only merge PRs. Releases are handled by @Alir3z4.

If you could ping me, I'd be happy to set the permission on pypi ;)

**Comment by jdufresne** [comment]
@Alir3z4  That'd be great. My PyPI username is jdufresne. Thanks.

**Comment by Alir3z4** [comment]
> @Alir3z4 That'd be great. My PyPI username is jdufresne. Thanks.

Awesome, done ;)

**Comment by jdufresne** [comment]
I have released a new version with this fix included. If you continue to experience issues let us know. Thanks for the report!
