### ISSUE TITLE
removal of unescape() broke rss2email

### ISSUE THREAD

**Issue by jahir** [Alir3z4/html2text#291]
Hi!

In #63 (commit 5443b50) unescape() was removed because it was said to be unused. Unfortunately, it is used by rss2email (at least the version that is shipped with Fedora). I know r2e is somewhat outdated (last release in 2011), but it was working quite fine.
Is there any chance of re-adding this function?

**Comment by jdufresne** [comment]
Could that package use the stdlib [`unescape`](https://docs.python.org/3/library/html.html#html.unescape) instead? As a matter of fact, looks like this was already done in the package https://github.com/rss2email/rss2email/commit/81824e25723dcd2936f25f64ebc16f2e8ec9f310

html2text is not intended as a collection of various utility functions. If the function is unused internally and not part of the documented API, the function is probably better served somewhere else.

**Comment by jahir** [comment]
The Fedora package contains the original rss2email, which is no longer developed (as I wrote, last updated 2011) and uses Python 2. Since that is deprecated and will no longer be supported or updated from 2020 on, this is a good time to update to the (more or less official) successor (which carries, confusingly, the same name). The Fedora package will eventually be updated as well, so this can safely be closed.
