### ISSUE TITLE
Unnecessary spaces around <b></b>

### ISSUE THREAD

**Issue by vyahhi** [Alir3z4/html2text#324]
The html code `X<b>one</b>, two` is translated into `X **one** , two\n\n`, but should be translated into `X**one**, two\n\n` instead (without spaces around **one**).

- Version by `html2text --version`: 2020.1.16

- Test script

```
import html2text
h = html2text.HTML2Text()
h.handle('X<b>one</b>, two')
```
- Python version `python --version`: 3.8.2

**Comment by snarfed** [comment]
Also happens with other inline tags, eg `(<em>foo</em> bar` is translated to `( __foo__ bar`.
