### ISSUE TITLE
img link in 'a href'

### ISSUE THREAD

**Issue by Alir3z4** [Alir3z4/html2text#33]
@dvasseur The following html code
````
<a href="http://google.com"><img src="images/google.png" alt="Go to google"></a>
````
is converted to ````[Go to google](images/google.png)````
I would have prefered, ````[Go to google](http://google.com)````

can this be done ?
- - -
@szepeviktor: This is so in Markdown:
[![Go to google](http://www.google.com/images/errors/logo_sm_2.png)](http://google.com)
```markdown
[![Go to google](images/google.png)](http://google.com)
```
- - -
@Alir3z4 Hmm, this is interesting actually:
```
In [2]: html2text.html2text('<a href="http://google.com"><img src="images/google.png" alt="Go to google"></a>')
Out[2]: u'![Go to google](images/google.png)\n\n'
```
Sure it has its own downside, but I would like to have base hostname in the image src too.
- - -
@szepeviktor: So the `<a>` element is completely stripped out?
- - -
@Alir3z4: That's another issue here and yes the a tag is gone here
- - -
@mcepl: Just for reference http://daringfireball.net/projects/markdown/syntax#img
- - -

*Note: Extracted from an old repo.*

**Comment by szepeviktor** [comment]
It is solved now?

**Comment by szepeviktor** [comment]
:smile: Yes it does.

```html
<a href="http://google.com"><img src="images/google.png" alt="Go to google"></a>
```

```
[![Go to google](images/google.png)](http://google.com)
```

**Comment by szepeviktor** [comment]
@Alir3z4 Please close it.

**Comment by Alir3z4** [comment]
@szepeviktor Thanks for the update and follow up on this issue.
I'll close now.
