### ISSUE TITLE
Change the license

### ISSUE THREAD

**Issue by jarekwg** [Alir3z4/html2text#366]
Hiya,

GPL3 is a strong copyleft license; it prevents this code from being used in commercial projects.

There was a similar issue raised originally here, which just quietly fell by the wayside: https://github.com/aaronsw/html2text/issues/41

This is a great library, but completely shuts out a large portion of the developer community. :/

Any chance we could get it changed to eg. MIT or BSD-3-CLAUSE or APACHE-2.0?

Cheers,

**Comment by Spoonrad** [comment]
I very strongly support this! Our company wants to use this library but this is completely impossible with the very restrictive licence you have chosen to use. Given that you do not have any commercial licencing available and are clearly not trying to make profit from this library, I would kindly request that you change the licence to a more flexible licence for companies that use proprietary software.

Would you envision this? I look forward to your feedback, thank you. :)

@Alir3z4

**Comment by devfox-se** [comment]
I support this proposal as well

**Comment by branislav-brujic** [comment]
I totally agree with you guys.

**Comment by danielpunkass** [comment]
I am also interested in a non-GPL-encumbered version of this library, but I'm not sure it would be too simple to change the license especially considering the originator of the library has passed away. You need to get permission from all the contributors to allow relicensing their code using the proposed license, at least as far as I understand things.

**Comment by adulau** [comment]
I'm strongly opposed to the change of the license (and you cannot change without having the approval of the contributors and all the author-rights owners).

The original author and contributors make contributions under a known open source license which protect also freedom and ensuring new contributions are kept under an open source license. 

If you don't like the license and don't support the copyleft philosophy, nothing block you to reimplement the software under a different license.

**Comment by Alir3z4** [comment]
Comment https://github.com/Alir3z4/html2text/issues/366#issuecomment-1374796496 has summaried it perfectly. (Than you @adulau )

Long live GPLv3 and copyleft philosophy.
