### ISSUE TITLE
Wraps long URLs

### ISSUE THREAD

**Issue by stefanor** [Alir3z4/html2text#38]
Forwarding aaronsw/html2text#7, so it doesn't get forgotten:
Forwarding http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=616090:

Long URLs are wrapped, which they probably shouldn't be.

Example:

    <html>
    <head><title>Test</title></head>
    <body>
    <p>And <a href="http://bugs.debian.org/cgi-bin/pkgreport.cgi?tag=multiarch;users=debian-dpkg@lists.debian.org">here</a> is a long link I had at hand.</p>
    </body>
    </html>

Results in:

    And [here][1] is a long link I had at hand.
    
       [1]: http://bugs.debian.org/cgi-bin/pkgreport.cgi?tag=multiarch;users
    =debian-dpkg@lists.debian.org

**Comment by jmagnusson** [comment]
Took me a while to find that `html2text` indirectly caused the `%0A` (newline in URL encoding) occurring in my links. I've temporarily disabled `body_width` wrapping in my code to prevent it.
```
parser = HTML2Text()
parser.body_width = 0
parser.handle(value)
```

**Comment by Alir3z4** [comment]
Hey @jmagnusson @stefanor 
I see these two hacks trying to fix the issue: 
* https://github.com/leonardoo/django-userena/commit/4b5dd731f5d39085b78a02fea2c94d229b3f8817
* https://github.com/emencia/emencia-django-newsletter/commit/a9adff758e56b949db8c1952bf3da541bf87fd47

Do you think we can apply the same into htmltext without explicitly set `body_width=0` ?

**Comment by theSage21** [comment]
@stefanor does this fix help?

**Comment by stefanor** [comment]
Yeah, combined with `--reference-links` that seems to do the right thing.

**Comment by theSage21** [comment]
@stefanor @Alir3z4  Consider closed?

**Comment by Alir3z4** [comment]
I'm going to close this then, thanks for your awesome collaboration on this ;)

**Comment by nguyenl95** [comment]
I still met this issue when the link contains special characters like "-". The link is broken when set word wrap.

**Comment by Alir3z4** [comment]
@nguyenl95 have you consider `--reference-links` ?

**Comment by nguyenl95** [comment]
I intend to use html2text as lib instead of command-line.
Btw I just found your /tests and wrapped it in function.

```python
def html2md(raw):
  h = html2text.HTML2Text()
  h.body_width = 0
  return h.handle(raw)
```

**Comment by Alir3z4** [comment]
@nguyenl95 Thanks for mentioning.
I didn't noticed you were referring to use of of the lib itself and not he CLI.

I'd love to see a pull request for updating the documentation so other can see and use it.
You would be modifying:

* https://github.com/Alir3z4/html2text/blob/master/docs/how_it_works.md
* https://github.com/Alir3z4/html2text/blob/master/docs/usage.md

Let me know if I can help you with anything else.

**Comment by nguyenl95** [comment]
Actually there is one feature I think of.

It is the limit of output, my forum platform doesn't allow my crawler to post the content over 32000 characters.

**Comment by Alir3z4** [comment]
@nguyenl95 Great, feel free to make a feature request or even better a pull request, I would love to know more about it.
