### ISSUE TITLE
Broken Images in README.md

### ISSUE THREAD

**Issue by guettli** [Alir3z4/html2text#385]
Broken Images in README.md 

See:

![image](https://user-images.githubusercontent.com/414336/161980123-7515b819-26f8-4c95-8d5c-e58aeff1bf2f.png)

**Comment by snarfed** [comment]
#343

**Comment by Alir3z4** [comment]
Fixed in https://github.com/Alir3z4/html2text/commit/ff0db816d31eeb711cf0299e94cbd99526325bdd
