### ISSUE TITLE
Why html2text module throws UnicodeDecodeError?

### ISSUE THREAD

**Issue by Alir3z4** [Alir3z4/html2text#47]
I have problem with html2text module...shows me UnicodeDecodeError:

    UnicodeDecodeError: 'ascii' codec can't decode byte 
    0xbe in position 6: ordinal not in range(128)

Example :

    #!/usr/bin/python
    # -*- coding: utf-8 -*-
    import html2text
    import urllib
    
    h = html2text.HTML2Text()
    h.ignore_links = True
    
    html = urllib.urlopen( "http://google.com" ).read()
    
    print h.handle( html )

...also have tried `h.handle( unicode( html, "utf-8" )`  with no success. Any help.
EDIT :

    Traceback (most recent call last):
      File "test.py", line 12, in <module>
        print h.handle(html)
      File "/home/alex/Desktop/html2text-master/html2text.py", line 254, in handle
        return self.optwrap(self.close())
      File "/home/alex/Desktop/html2text-master/html2text.py", line 266, in close
        self.outtext = self.outtext.join(self.outtextlist)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xbe in position 6: ordinal not in range(128)

Source: http://stackoverflow.com/q/24755022/636136

**Comment by theSage21** [comment]
I am not sure what the issue is here. The SO question above shows why the error is happening and it is based on the way the user uses the library.
