### ISSUE TITLE
Backslash getting inserted before multiple dashes

### ISSUE THREAD

**Issue by philfreo** [Alir3z4/html2text#48]
Anyone have an explanation or fix for this? It seems like a bug to me.

I'm running version `2014.12.5`

```
In [11]: print html2text.html2text('-').strip()
-

In [12]: print html2text.html2text('--').strip()
\--

In [13]: print html2text.html2text('------').strip()
\------
```

**Comment by theSage21** [comment]
The multiple dashes are used in MD to mark headers and so are escaped. For reference look [here](http://daringfireball.net/projects/markdown/syntax#header).

**Comment by Alir3z4** [comment]
I'm going to close this, please feel free to re-open.

**Comment by sowinski** [comment]
Is it possible to turn of this feature?
