### ISSUE TITLE
html2text fails on daringfireball

### ISSUE THREAD

**Issue by 1n1r2** [Alir3z4/html2text#54]
I couldn't figure out how to resolve this myself.

Install on cygwin with python 2.7
html2text seems to work on many sites:

html2text https://michelf.ca/projects/php-markdown/extra

But not on Gruber's standard syntax:

html2text http://daringfireball.net/projects/markdown/syntax

The reason for extracting syntax from daringfireball is the gray-background pages are so hard to read.

Nice application;  I look forward to studying the html2text python code to learn.

**Comment by mcepl** [comment]
a) WORKSFORME ... the command line you show doesn't give any error and produces (IMHO) correct Markdown output (python 2.7.5, html2text from the master branch)
b) if you have some error, please, include it here.

**Comment by Alir3z4** [comment]
Marked as `invalid` and `wontfix`.

Please feel free to re-open if you facing the issue and have some errors to include and some way to reproduce.
