### ISSUE TITLE
Spaces inside and around links are concatenated

### ISSUE THREAD

**Issue by aykevl** [Alir3z4/html2text#58]
When there's a space before a link and before the link's content, both are preserved:

```
~$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import html2text
>>> h = html2text.HTML2Text()
>>> h.handle('foo <a href="/"> bar</a>')
u'foo [ bar](/)\n\n'
>>> h.ignore_links = True
>>> h.handle('foo <a href="/"> bar</a>')
u'foo  bar\n\n'
>>> html2text.__version__
'2014.12.29'
```

Browsers strip the text inside the link:

> foo <a href="/"> bar</a>

This is html2text installed from pip, on Debian jessie.

**Comment by Alir3z4** [comment]
I don't think this is a big bug.
Spaces and half-spaces should be preserved for some formatting reasons.


I'll leave this issue here for now, but It shouldn't be considered as a bug.
Although formatting options/flags are welcome.

*half-spaces*: *In Persian based languages such as Arabic, Farsi, Dari, etc is a must. Words like می باشد  and می‌باشد are such examples.*

**Comment by theSage21** [comment]
I do not understand the issue? Is the preservation of spaces the bug in question?

**Comment by aykevl** [comment]
I had to work aroud this bug in another project, as the text version was showing two spaces where the HTML version (in an email) was showing only one space as intended.

As an additional argument, when the spaces are at one side of the link tag, html2text *only outputs one space*:

```
>>> h.handle('foo  <a href="/">bar</a>')
u'foo [bar](/)\n\n'
>>> h.handle('foo<a href="/">  bar</a>')
u'foo[ bar](/)\n\n'
>>> h.ignore_links = True
>>> h.handle('foo  <a href="/">bar</a>')
u'foo bar\n\n'
>>> h.handle('foo<a href="/">  bar</a>')
u'foo bar\n\n'
```

Just like browsers do:
> foo  <a href="/">bar</a>
> foo<a href="/">  bar</a>

Note that the space in the second example is part of the link (in Chrome).

I don't know how non-Latin-based languages do this formatting.

@theSage21 the problem is that there are two spaces rendered where there should be (in my opinion and as browsers indicate) only one.

**Comment by theSage21** [comment]
A browser renders one space irrespective of how many spaces are there between two words.
Creating a file `sample.html` or testing [here](http://htmledit.squarefree.com/) with the following html

```
<p>arjoonn sharma
<br>
arjoonn                     sharma</p>
```

shows that the spaces do not matter and only one space is rendered even though the html is evidently not the same.

@aykevl My point being that html2text preserves information from the original html and translates that to text.

**Comment by Alir3z4** [comment]
As @mcepl once mentioned can we transform the data to its original form or we gonna loose the format of the original.

We're fine with any implementations as long as the text can keep it's original form after parsing to html by python markdown parser.

@mcepl do you have any inputs on this?

**Comment by Alir3z4** [comment]
Not a `bug` and based on https://github.com/Alir3z4/html2text/issues/58#issuecomment-113105206 I'll close this.
