### ISSUE TITLE
[Enhancement] Automatic version number

### ISSUE THREAD

**Issue by the01** [Alir3z4/html2text#62]
I would like to propose a way to automatically load the version info from the package (__init__.py) into setup.py:

```python
def get_version():
    import os
    import re
    init_file = os.path.join("html2text", "__init__.py")
    init_lines = open(init_file, 'rt').readlines()
    version_re = r"^__version__ = ['\"]([^'\"]*)['\"]"
    for line in init_lines:
        mo = re.search(version_re, line, re.M)
        if mo:
            return mo.group(1)
    raise RuntimeError(u"Unable to find version string in {}".format(init_file))
```
and then you just do
```python
setup(
    name="html2text",
    version=get_version(),
    ...
)
```
Adapted from [stackoverflow.com](http://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package)

**Comment by Alir3z4** [comment]
Good idea, I do this in other projects that I maintain.

* https://github.com/Alir3z4/python-short_url/blob/master/setup.py#L8
* https://github.com/Alir3z4/python-short_url/blob/master/short_url/__init__.py#L50

lemme know what you think about it ;)

**Comment by the01** [comment]
Using __import__() with .__version__ is certainly cleaner, but the problem is that you actually import that file, meaning you are running code here. Say if you had some further imports in the __init__-file, those would get imported too and so on and so on. You might end up with race conditions or difficulties with relative imports...
That's why I went for the more inelegant version of parsing the file line by line while applying a regex.
Well, my 2 cents on the topic..
