### ISSUE TITLE
Link titles lost.

### ISSUE THREAD

**Issue by theSage21** [Alir3z4/html2text#69]
`<a href="htt://example.com" title="Title"> an example</a> inline link.`

Produces

`This is [ an example](http://example.com/) inline link.`

when 

`This is [ an example](http://example.com/ "Title") inline link.`

is expected as per Daring Fireball.

**Comment by Alir3z4** [comment]
I mark this as `enhancement` not a `bug`.

**Comment by theSage21** [comment]
In the [init file](https://github.com/Alir3z4/html2text/blob/master/html2text/__init__.py) line 667 and 668,
I think an attempt is made to add link titles. Am I wrong? If I am what is this piece of code doing?

**Comment by theSage21** [comment]
Link titles were lost in inline links.
```
h = html2text.HTML2Text()
h.inline_links = False
print(h.handle('<a href="http://example.com" title="Title"> an example</a>'))
```
gives us
```
[ an example] [1]

[1]: http://example.com (Title)
```
while doing
```
h = html2text.HTML2Text()
h.inline_links = False
print(h.handle('<a href="http://example.com" title="Title"> an example</a>'))
```
gives us
```
[ an example] (http://example.com)
```
The 'Title' attribute is lost in the inline style links.
Just putting it here so that people know what was wrong.
