### ISSUE TITLE
Make all available options command line flags?

### ISSUE THREAD

**Issue by theSage21** [Alir3z4/html2text#81]
A lot of the options html2text supports are not available via the command line.

Making them available as command line flags should be nice for a lot of people.

@Alir3z4 Thoughts?

**Comment by Alir3z4** [comment]
@theSage21 Yeah, that is required for sure.
I agree all the options should be available as flags on CLI as well.

**Comment by theSage21** [comment]
#82 Solves this and introduces more tests.
