### ISSUE TITLE
Body width not working with lists

### ISSUE THREAD

**Issue by strang3quark** [Alir3z4/html2text#85]
I use the body_width property to limit the width of the text but it seems not to be working for lists.

**Comment by Alir3z4** [comment]
@strang3quark Do you think #84 will be a good way to fix this ?

**Comment by theSage21** [comment]
@strang3quark Right. Will be working on this. Is this what you are experiencing?
```
<ul>
    <li>
        <ul>
            <li>
                <ul>
                    <li>asdgsdfdsfasdfsadfasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasfdsglkjsdlgjsdljvld</li>
                    <li>asdgsdfdsfasdfsadfasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasfdsglkjsdlgjsdljvld</li>
                    <li>asdgsdfdsfasdfsadfasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasfdsglkjsdlgjsdljvld</li>
                    <li>asdgsdfdsfasdfsadfasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasfdsglkjsdlgjsdljvld</li>
                </ul>
            aqweqwtrqwtqwrqwr</li>
            <li>qweqwcklmlcmkkajsdkljlkwmqcqlmcasjdfaslnfdn v,mancmaslkdaldjqwidnl asmldk alsdamskdaskdaslkfjasklfaqweqwtrqwtqwrqwr</li>
            <li>qweqwcklmlcmkkajsdkljlkwmqcqlmcasjdfaslnfdn v,mancmaslkdaldjqwidnl asmldk alsdamskdaskdaslkfjasklfaqweqwtrqwtqwrqwr</li>
            <li>qweqwcklmlcmkkajsdkljlkwmqcqlmcasjdfaslnfdn v,mancmaslkdaldjqwidnl asmldk alsdamskdaskdaslkfjasklfaqweqwtrqwtqwrqwr</li>
        </ul>
    </li>
    <li>poqwoirpoqwpcqpasdoiaspfjanfladsnclqeiofjqjdfklqklcmaklsmckljzklcaklsmdlkasdklajdklwamcklqwmclacm</li>
    <li>poqwoirpoqwpcqpasdoiaspfjanfladsnclqeiofjqjdfklqklcmaklsmckljzklcaklsmdlkasdklajdklwamcklqwmclacm</li>
    <li>poqwoirpoqwpcqpasdoiaspfjanfladsnclqeiofjqjdfklqklcmaklsmckljzklcaklsmdlkasdklajdklwamcklqwmclacm</li>
    <li>poqwoirpoqwpcqpasdoiaspfjanfladsnclqeiofjqjdfklqklcmaklsmckljzklcaklsmdlkasdklajdklwamcklqwmclacm</li>
    <li>poqwoirpoqwpcqpasdoiaspfjanfladsnclqeiofjqjdfklqklcmaklsmckljzklcaklsmdlkasdklajdklwamcklqwmclacm</li>
</ul>
```
This text spills over the body width specified. correct?

**Comment by strang3quark** [comment]
@theSage21 yes, but it appears that it's not only related with lists.

This is the code I'm using:
```
  def htmlToText(self,content,cols, showImgTags = False):
        parser = html2text.HTML2Text(bodywidth=cols)                    
        parser.images_with_size = showImgTags
        #parser.images_to_alt = not(showImgTags)
        parser.inline_links = False
        return parser.handle(content)
```

There is a screenshot:
![2015-07-01_02 54 44](https://cloud.githubusercontent.com/assets/9934377/8446058/b1a2ed52-1f9c-11e5-85b5-d782afd2d022.png)

**Comment by theSage21** [comment]
@strang3quark Could you put the actual `html` here? I do not want to type all of that out. :smile:

**Comment by strang3quark** [comment]
Sorry

https://gist.github.com/strang3quark/1008cf43ba3916867569

**Comment by theSage21** [comment]
@strang3quark I do not know how lists should be formatted when wrapped. Possibly something like this? Constant indent. As for the `pre` tags I think the wrapping should be avoided.
```
*  first element which was too long to fit
   on one line.
*  second element which was too long to fit
   on one line.
```

**Comment by theSage21** [comment]
@strang3quark List wrapping is specifically suspended by [this](https://github.com/Alir3z4/html2text/blob/master/html2text/utils.py#L193) code. @Alir3z4 Should we change? Changing this will break a lot of people's code.

**Comment by Alir3z4** [comment]
@theSage21 Thanks for doing a good inspection.
wrapping should not be done on lists. Please don't change the code and it let it behave as before.

**Comment by theSage21** [comment]
@strang3quark as a fix for your problem you can comment out the said lines. `skipwrap` function in utils.py controls what to skip. Commenting out parts of the code should help you out.

**Comment by strang3quark** [comment]
@theSage21 Ok, thanks.

**Comment by theSage21** [comment]
@Alir3z4 Close the issue? Is there something I missed?
