### ISSUE TITLE
Very slow if input has long sections without spaces

### ISSUE THREAD

**Issue by philfreo** [Alir3z4/html2text#90]
When running `html2text` on some HTML with a base64-encoded image in an `<img>` tag I notice really poor performance of html2text.

I narrowed it down to seeing the problem when a long string appears without spaces (e.g. what you see with a base64 image):

```
In [30]: html = 'x' * 25000
In [31]: %time c = html2text.html2text(html)
Wall time: 11.7 s
```

You'll notice that a string twice as long (but with spaces) runs 200x faster:

```
In [33]: html = 'x ' * 25000
In [34]: %time c = html2text.html2text(html)
Wall time: 48.8 ms
```

Thoughts?

**Comment by theSage21** [comment]
It seems that there is a bottle neck in joining strings during wrapping. Performing line_profiler test we get  [result1](https://gist.github.com/theSage21/11904a3b76dba0466214).

Test script was
```
import html2text
html = 'x' * 2500
md = html2text.html2text(html)
```
The slowdown might be caused due to using `+=` instead of an available function like `join`.

**Comment by theSage21** [comment]
@philfreo On tinkering with this and looking on the Internet, I found this.

<http://stackoverflow.com/questions/11781261/why-are-textwrap-wrap-and-textwrap-fill-so-slow>
The problem arises from `from textwrap import wrap`.
Textwrap performs terribly on unbreakable strings.
@Alir3z4 inputs?

**Comment by theSage21** [comment]
@philfreo @Alir3z4 what should be the behavior for unbroken strings? Do we simply chop them up into 'n' length pieces or keep them intact? Current code would expect them to be unbroken as wrap does not break them.

**Comment by theSage21** [comment]
Since the slow code resides in another library and the cause is computational cost, there is no getting around it. You could introduce a behaviour which simply performs chopping in the case of no spaces instead of word aware wrapping.
