### ISSUE TITLE
Redundant \n causes link breakage 

### ISSUE THREAD

**Issue by jonathan-s** [Alir3z4/html2text#92]
This snippet ->
> <p>MongoDB helps us scale for the expanding volumes of data we collect in our <a href="https://www.serverdensity.com/" title="Server Monitoring Software">server monitoring</a> service. Over the years, we went from processing 40GB per month, to <a href="https://www.serverdensity.com/server-monitoring/#graphing" title="Server Density Monitoring Graphs">more than 250TB</a>.</p>

generates the following code for me ->
> MongoDB helps us scale for the expanding volumes of data we collect in our\n[server monitoring](https://www.serverdensity.com/ "Server Monitoring\nSoftware" ) service. Over the years, we went from processing 40GB per month,\nto [more than 250TB](https://www.serverdensity.com/server-monitoring/#graphing\n"Server Density Monitoring Graphs" ).\n\n

You can see the "\n" at some places, including some that would break the link entirely. There is no reason that there would be an extra space at the very end of `"Server Density Monitoring Graphs"` that also breaks the link. 

Apparently it doesn't break the links for the parser of github, but other markdown parsers aren't able to handle it gracefully. So I would still consider it a bug.

**Comment by theSage21** [comment]
Um.. I do not understand. Providing text as input causes you to receive text with extra line breaks as output?  
Could you provide the raw html that is causing this problem?

**Comment by jonathan-s** [comment]
This would be the raw html. 
```
<p>MongoDB helps us scale for the expanding volumes of data we collect in our <a href="https://www.serverdensity.com/" title="Server Monitoring Software">server monitoring</a> service. Over the years, we went from processing 40GB per month, to <a href="https://www.serverdensity.com/server-monitoring/#graphing" title="Server Density Monitoring Graphs">more than 250TB</a>.</p>
```
Is it possible to disable wrapping? To me it seems like wrapping is often not that desirable. Rather you'd want the editor or what have you do the wrapping for you, instead of hardcoding the wrapping.

**Comment by theSage21** [comment]
- You can switch off wrapping as shown in the [docs](https://github.com/Alir3z4/html2text/blob/master/docs/usage.md) by setting `BODY_WIDTH` to `0`.
- The default behavior is wrapping, you will have to take it up with @Alir3z4 
- Using the provided html and the same script I get
```
<p>MongoDB helps us scale for the expanding volumes of data we collect in our <a href="https://www.serverdensity.com/" title="Server Monitoring Software">server monitoring</a> service. Over the years, we went from processing import 40GB per month, to <a href="https://www.serverdensity.com/server-monitoring/#graphing" title="Server Density Monitoring Graphs">more than 250TB</a>.</p>
----------
MongoDB helps us scale for the expanding volumes of data we collect in our
[server monitoring](https://www.serverdensity.com/ "Server Monitoring
Software" ) service. Over the years, we went from processing import 40GB per
month, to [more than 250TB](https://www.serverdensity.com/server-
monitoring/#graphing "Server Density Monitoring Graphs" ).
```
- When I switch off wrapping by calling `html2text.html2text(html, bodywidth=0)` I get
```
<p>MongoDB helps us scale for the expanding volumes of data we collect in our <a href="https://www.serverdensity.com/" title="Server Monitoring Software">server monitoring</a> service. Over the years, we went from processing import 40GB per month, to <a href="https://www.serverdensity.com/server-monitoring/#graphing" title="Server Density Monitoring Graphs">more than 250TB</a>.</p>
----------
MongoDB helps us scale for the expanding volumes of data we collect in our [server monitoring](https://www.serverdensity.com/ "Server Monitoring Software" ) service. Over the years, we went from processing import 40GB per month, to [more than 250TB](https://www.serverdensity.com/server-monitoring/#graphing "Server Density Monitoring Graphs" ).
```
Does that help?

**Comment by Alir3z4** [comment]
I have labeled this issue as `invalid`.
@theSage21 Thanks for taking care of it.
