### ISSUE TITLE
how to disable escape '-'?

### ISSUE THREAD

**Issue by askovpen** [Alir3z4/html2text#97]
``` html
<p>- test</p>
```

why result?

```
\- test
```

how to disable escape '-'?

**Comment by theSage21** [comment]
I do not suppose there is a way since a `- <something>` in markdown indicates an unordered list.  
You can use a `-<something>` to avoid the escaping. Note the absence of a space in between the minus and `<something>`.

@Alir3z4 am I mistaken?

**Comment by Alir3z4** [comment]
@theSage21 The issue that @askovpen is addressing is a follow up on https://github.com/aaronsw/html2text/issues/101 which I refer him to this repo.

Anyway, I didn't know there's no way to turn off the escaping. @theSage21 are you sure ?

**Comment by theSage21** [comment]
For the reasons you mentioned in aaronsw#101 escaping this is not possible. There might be use cases requiring that the text be left as is. Turning off markdown mode I mean? @askovpen what is your use case? If there are plenty of use cases that require markdown to be removed, it might make sense to have a `--no-markdown` option.

Otherwise it might be nice to point people to another repo which converts Markdown to normal text.

**Comment by askovpen** [comment]
@theSage21  i  parse with feedparser livejournal rss, parse posts body with html2text and post it to facebook.

**Comment by askovpen** [comment]
@theSage21 e.g: http://ru-auto.livejournal.com/39911818.html -> https://www.facebook.com/ru.auto.lj/posts/1064178320288493

**Comment by theSage21** [comment]
@askovpen This might help.

```
escapable = '][)(_*}{!#-'
while True:
    try:
        x = input()
    except EOFError:
        break
    else:
        for char in escapable:
            x = x.replace('\\' + char, char)
        print(x)
```

@Alir3z4 if another issue comes up with a similar usecase, it might be worthwhile to put this feature in.

**Comment by Alir3z4** [comment]
@theSage21 Agree on that.

**Comment by theSage21** [comment]
@askovpen @Alir3z4 Sould we consider this closed or do you want to keep it open for a vote purpose?

**Comment by Alir3z4** [comment]
I say let's keep it open for future request and votes, if more people ask for this then we'll consider.

**Comment by Sorrow2** [comment]
vote for this feature.
i use html2text to post to telegram. And i have plenty of cases when line starts with '-'.
Should i just use .replace('\\','') for now?

**Comment by theSage21** [comment]
@Sorrow2 If you could do a PR that would be great since it might take me some time to get to this.
